# MochaArch - unpackfs inicial
# Caminhos finais dependem da estrutura da ISO.
---
unpack:
    - source: "/run/archiso/bootmnt/arch/x86_64/airootfs.sfs"
      sourcefs: "squashfs"
      destination: ""
