---
showSupportUrl: true
showKnownIssuesUrl: true
showReleaseNotesUrl: false
showDonateUrl: true
requirements:
  requiredStorage: 40
  requiredRam: 1.0
  internetCheckUrl: https://archlinux.org/
  check:
  - storage
  - ram
  - power
  - internet
  - root
  - screen
  required:
  - ram
geoip:
  style: none
  url: https://geoip.kde.org/v1/ubiquity
  selector: CountryCode
requiredStorage: 40
requiredRam: 4.0
internetCheckUrl: https://archlinux.org/
check:
- storage
- ram
- power
- internet
- root
- screen
required:
- storage
- ram
- root
- screen
