# MochaArch — agressividade FPS / memória V4
# Padrão canônico para jogos/Steam/Proton/Wine.
vm.swappiness = 133
vm.vfs_cache_pressure = 50
vm.page-cluster = 0
vm.dirty_background_bytes = 67108864
vm.dirty_bytes = 268435456
vm.max_map_count = 8388608
