# MochaArch — MangoHud canônico
# Ativado pelo wrapper e pelo lançador Steam Mocha.

legacy_layout=false
horizontal
background_alpha=0.35
font_size=20

fps
frametime
gpu_stats
gpu_temp
gpu_load_change
gpu_load_value=60,90
vram
cpu_stats
cpu_temp
ram
gamemode
vkbasalt
wine
engine_version
arch
time
time_format=%H:%M

toggle_hud=Shift_R+F12
toggle_logging=Shift_L+F2
reload_cfg=Shift_L+F4
