# MochaArch - Calamares settings inicial
# Arquivo de desenvolvimento. Não copiar para /etc/calamares da máquina atual sem teste.
---
modules-search:
  - local
  - /usr/lib/calamares/modules

branding: mocha

prompt-install: false
dont-chroot: false
oem-setup: false
disable-cancel: false

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - machineid
      - fstab
      - locale
      - keyboard
      - users
      - displaymanager
      - initramfs
      - bootloader
      - umount
  - show:
      - finished
